config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.class_hello
    'Hello User'
  end

  # @return [String] a hello message.
  def hello
    "Hello #{self.first_name} #{last_name}"
  end

  # @return [Integer] the number of words in bio.
  def bio_word_count
    return 0 if bio.nil?
    words = bio.scan(/\w+/)
    words.size
  end


  def full_name
    first_name+' '+last_name
  end

  private

    def private_hello
      "Hello #{self.first_name} from private method!"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to :users
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PryDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1 style="text-align: center">Users</h1>

<% for user in @users %>
  <div style="margin:auto; width: 200px; border: 1px solid; margin-bottom: 5px; text-align: center;">
    <h4><%= link_to user.full_name, user %></h4>
  </div>
<% end %>

app/views/users/show.html.erb
<div style="width: 300px; margin:auto; background-color: #eee; border: 1px solid;">
  <h1 style="text-align:center"><%= @user.first_name %></h1>
  <div style="text-align:center"><%= @user.hello %></div>
  <br/>
  <p style="padding: 5px;">
    <%= @user.bio %>
  </p>
  <div style="color:red; font-weight:bold; text-align:center; font-weight: 10px"><%= @user.bio_word_count %> words</div>
</div>
<br/>
<br/>
<div style="text-align:center">
  <%= link_to 'Go back', users_url %>
</div>